[colors.primary]
background = "#0f0c01"
foreground = "#c8bea0"

[colors.normal]
black = "#0f0c01"
red = "#6A5C1C"
green = "#5D5B37"
yellow = "#7A7F7D"
blue = "#8C6911"
magenta = "#8D641D"
cyan = "#8A7652"
white = "#c8bea0"

[colors.bright]
black = "#8c8570"
red = "#6A5C1C"
green = "#5D5B37"
yellow = "#7A7F7D"
blue = "#8C6911"
magenta = "#8D641D"
cyan = "#8A7652"
white = "#c8bea0"
